/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_jorgezuniga;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        DefaultComboBoxModel modeloSexoA = (DefaultComboBoxModel) GeneroAlumno.getModel();
        modeloSexoA.addElement("Masculino");
        modeloSexoA.addElement("Femenino");
        GeneroAlumno.setModel(modeloSexoA);

        DefaultComboBoxModel modeloSexoM = (DefaultComboBoxModel) GeneroMaestro.getModel();
        modeloSexoM.addElement("Masculino");
        modeloSexoM.addElement("Femenino");
        GeneroAlumno.setModel(modeloSexoM);

        DefaultComboBoxModel modeloCarrera = (DefaultComboBoxModel) NombresCarreras.getModel();
        modeloCarrera.addElement("Finanzas");
        modeloCarrera.addElement("Derecho");
        modeloCarrera.addElement("Administracion de Empresas");
        modeloCarrera.addElement("Diseño Grafico");
        modeloCarrera.addElement("Mercadotecnia");
        modeloCarrera.addElement("Sistemas Computacionales");
        modeloCarrera.addElement("Industrial");
        modeloCarrera.addElement("Mecatronica");
        modeloCarrera.addElement("Biomedica");
        modeloCarrera.addElement("Energia");
        modeloCarrera.addElement("Medicina");
        modeloCarrera.addElement("Cirugía");
        modeloCarrera.addElement("Odontología");
        modeloCarrera.addElement("Nutrición");
        modeloCarrera.addElement("Terapia Física");
        modeloCarrera.addElement("Ocupacional");
        NombresCarreras.setModel(modeloCarrera);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Master = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenu();
        Nombre = new javax.swing.JMenuItem();
        Apellido = new javax.swing.JMenuItem();
        Edad = new javax.swing.JMenuItem();
        Salario = new javax.swing.JMenuItem();
        Clases = new javax.swing.JPopupMenu();
        EliminarClases = new javax.swing.JMenuItem();
        ModificarClases = new javax.swing.JMenu();
        NombreClases = new javax.swing.JMenuItem();
        Seccion = new javax.swing.JMenuItem();
        Edificion = new javax.swing.JMenuItem();
        Salon = new javax.swing.JMenuItem();
        Carrera = new javax.swing.JPopupMenu();
        EliminarCar = new javax.swing.JMenuItem();
        ModificarCarrera = new javax.swing.JMenu();
        SalarioModi = new javax.swing.JMenuItem();
        JefeCar = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NombreAlumno = new javax.swing.JTextField();
        ApellidoAlumno = new javax.swing.JTextField();
        EdadAlumno = new javax.swing.JFormattedTextField();
        GeneroAlumno = new javax.swing.JComboBox<>();
        CarreraAlumno = new javax.swing.JComboBox<>();
        GuardarAlumno = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ClasesMaestro = new javax.swing.JComboBox<>();
        GuardarMaestro = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        GeneroMaestro = new javax.swing.JComboBox<>();
        NombreMaestro = new javax.swing.JTextField();
        ApellidoMaestro = new javax.swing.JTextField();
        SalarioMaestro = new javax.swing.JFormattedTextField();
        EdadMestro = new javax.swing.JFormattedTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        AireAcondicionadoClase = new javax.swing.JComboBox<>();
        SeccionClase = new javax.swing.JTextField();
        NombreClase = new javax.swing.JTextField();
        GuardarClase = new javax.swing.JButton();
        EdificioClase = new javax.swing.JFormattedTextField();
        SalonClase = new javax.swing.JFormattedTextField();
        jPanel7 = new javax.swing.JPanel();
        NombresCarreras = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        CostoMensualCarrera = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        JefeCarrera = new javax.swing.JTextField();
        GuardarCarrera = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaMaestros = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaCarreras = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaAlumnos = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        ListaClases = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        Master.add(Eliminar);

        Modificar.setText("modificar");

        Nombre.setText("Nombre");
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        Modificar.add(Nombre);

        Apellido.setText("Apellido");
        Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoActionPerformed(evt);
            }
        });
        Modificar.add(Apellido);

        Edad.setText("Edad");
        Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadActionPerformed(evt);
            }
        });
        Modificar.add(Edad);

        Salario.setText("Salario");
        Salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalarioActionPerformed(evt);
            }
        });
        Modificar.add(Salario);

        Master.add(Modificar);

        EliminarClases.setText("Eliminar");
        EliminarClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarClasesActionPerformed(evt);
            }
        });
        Clases.add(EliminarClases);

        ModificarClases.setText("modificar");

        NombreClases.setText("Nombre");
        NombreClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreClasesActionPerformed(evt);
            }
        });
        ModificarClases.add(NombreClases);

        Seccion.setText("Apellido");
        Seccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeccionActionPerformed(evt);
            }
        });
        ModificarClases.add(Seccion);

        Edificion.setText("Edad");
        Edificion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdificionActionPerformed(evt);
            }
        });
        ModificarClases.add(Edificion);

        Salon.setText("Salario");
        Salon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalonActionPerformed(evt);
            }
        });
        ModificarClases.add(Salon);

        Clases.add(ModificarClases);

        EliminarCar.setText("Eliminar");
        EliminarCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCarActionPerformed(evt);
            }
        });
        Carrera.add(EliminarCar);

        ModificarCarrera.setText("Modificar");

        SalarioModi.setText("jMenuItem2");
        SalarioModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalarioModiActionPerformed(evt);
            }
        });
        ModificarCarrera.add(SalarioModi);

        JefeCar.setText("Jefe");
        JefeCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JefeCarActionPerformed(evt);
            }
        });
        ModificarCarrera.add(JefeCar);

        Carrera.add(ModificarCarrera);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Nombre");

        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Apellido");

        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Edad");

        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Genero");

        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Carrera");

        try {
            EdadAlumno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        GeneroAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroAlumnoActionPerformed(evt);
            }
        });

        CarreraAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarreraAlumnoActionPerformed(evt);
            }
        });

        GuardarAlumno.setText("Guardar");
        GuardarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarAlumnoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CarreraAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NombreAlumno)
                    .addComponent(ApellidoAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(EdadAlumno)
                    .addComponent(GeneroAlumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(GuardarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ApellidoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(EdadAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(GeneroAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CarreraAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(GuardarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Alumno", jPanel2);

        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Nombre");

        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Apellido");

        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Salario");

        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("Edad");

        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("Clases que imparte");

        GuardarMaestro.setText("Guardar");
        GuardarMaestro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarMaestroMouseClicked(evt);
            }
        });

        jLabel20.setForeground(new java.awt.Color(0, 0, 153));
        jLabel20.setText("Genero");

        GeneroMaestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroMaestroActionPerformed(evt);
            }
        });

        ApellidoMaestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoMaestroActionPerformed(evt);
            }
        });

        try {
            EdadMestro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClasesMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(SalarioMaestro, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NombreMaestro, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(GeneroMaestro, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ApellidoMaestro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                            .addComponent(EdadMestro)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(GuardarMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NombreMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ApellidoMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(GeneroMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(SalarioMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(EdadMestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ClasesMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(GuardarMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Maestro", jPanel3);

        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("Nombre");

        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("Seccion");

        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setText("Edificio");

        jLabel15.setForeground(new java.awt.Color(0, 0, 153));
        jLabel15.setText("Salon");

        jLabel16.setForeground(new java.awt.Color(0, 0, 153));
        jLabel16.setText("Aire acondicionado");

        AireAcondicionadoClase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        GuardarClase.setText("Guardar");
        GuardarClase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarClaseMouseClicked(evt);
            }
        });

        try {
            EdificioClase.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            SalonClase.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EdificioClase)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(AireAcondicionadoClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(NombreClase)
                            .addComponent(SeccionClase)
                            .addComponent(SalonClase)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(GuardarClase, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(199, 199, 199))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(NombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(SeccionClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(EdificioClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(SalonClase))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(AireAcondicionadoClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(GuardarClase, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Clase", jPanel6);

        jLabel1.setText("Nombre de la carrera");

        jLabel18.setText("Costo Mensual");

        try {
            CostoMensualCarrera.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel19.setText("Jefe de carrera");

        GuardarCarrera.setText("Guardar");
        GuardarCarrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarCarreraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GuardarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NombresCarreras, 0, 190, Short.MAX_VALUE)
                            .addComponent(CostoMensualCarrera)
                            .addComponent(JefeCarrera))))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombresCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(CostoMensualCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(JefeCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(GuardarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        jTabbedPane2.addTab("Carrera", jPanel7);

        jTabbedPane1.addTab("Agregar", jTabbedPane2);

        ListaMaestros.setModel(new DefaultListModel());
        ListaMaestros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaMaestrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListaMaestros);

        jTabbedPane3.addTab("Maestros", jScrollPane2);

        ListaCarreras.setModel(new DefaultListModel());
        ListaCarreras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaCarrerasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ListaCarreras);

        jTabbedPane3.addTab("Carreras", jScrollPane3);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Facultad");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTree1);

        jTabbedPane3.addTab("Arbol", jScrollPane4);

        ListaAlumnos.setModel(new DefaultListModel()
        );
        ListaAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaAlumnos);

        jTabbedPane3.addTab("Alumnos", jScrollPane1);

        ListaClases.setModel(new DefaultListModel()
        );
        ListaClases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaClasesMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(ListaClases);

        jTabbedPane3.addTab("Clases", jScrollPane5);

        jTabbedPane1.addTab("Modificar y Eliminar", jTabbedPane3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GeneroMaestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroMaestroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneroMaestroActionPerformed

    private void GuardarAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarAlumnoMouseClicked
        // TODO add your handling code here:
        try {
            String nombre, apellido, genero = "", Carrera;
            int edad, ID;
            if (CarreraAlumno.getSelectedIndex() >= 0) {
                Carrera = CarreraAlumno.getSelectedItem().toString();
                nombre = NombreAlumno.getText();
                apellido = ApellidoAlumno.getText();
                if (GeneroAlumno.getSelectedItem() == "Masculino") {
                    genero = "Masculino";
                }
                if (GeneroAlumno.getSelectedItem() == "Femenino") {
                    genero = "Femenino";
                }
                edad = Integer.parseInt(EdadAlumno.getText());
                ID = 0 + ran.nextInt(1000);

                DefaultListModel modelo = (DefaultListModel) ListaAlumnos.getModel();

                modelo.addElement(new Alumnos(ID, Carrera, nombre, apellido, edad, genero));
                ListaAlumnos.setModel(modelo);
                NombreAlumno.setText("");
                ApellidoAlumno.setText("");
                CarreraAlumno.setSelectedIndex(0);
                EdadAlumno.setText("");
                GeneroAlumno.setSelectedIndex(0);
                JOptionPane.showMessageDialog(this, "Se guardo con exito!!");
            } else {
                JOptionPane.showMessageDialog(this, "No hay Carrera que seleccionar!!\n"
                        + "Cree una :)");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error!");
        }
    }//GEN-LAST:event_GuardarAlumnoMouseClicked

    private void CarreraAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarreraAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarreraAlumnoActionPerformed

    private void GeneroAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneroAlumnoActionPerformed

    private void GuardarMaestroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarMaestroMouseClicked
        // TODO add your handling code here:
        try {
            if (ClasesMaestro.getSelectedIndex() >= 0) {
                String nombre, apellido, clase, genero = "";
                int salario, edad;
                nombre = NombreMaestro.getText();
                apellido = ApellidoMaestro.getText();
                salario = Integer.parseInt(SalarioMaestro.getText());
                edad = Integer.parseInt(EdadMestro.getText());

                if (GeneroMaestro.getSelectedItem() == "Masculino") {
                    genero = "Masculino";
                }
                if (GeneroMaestro.getSelectedItem() == "Femenino") {
                    genero = "Femenino";
                }
                clase = ClasesMaestro.getSelectedItem().toString();
                DefaultListModel modelo = (DefaultListModel) ListaMaestros.getModel();
                modelo.addElement(new Maestro(salario, nombre, apellido, edad, genero, clase));
                ListaMaestros.setModel(modelo);
                ClasesMaestro.setSelectedIndex(0);
                GeneroMaestro.setSelectedItem(0);
                NombreMaestro.setText("");
                ApellidoMaestro.setText("");
                EdadMestro.setText("");
                SalarioMaestro.setText("");
                JOptionPane.showMessageDialog(this, "Guardado exitosamente!!");
            } else {
                JOptionPane.showMessageDialog(this, "Mientras no hayan clases no puede haber maestros!!");
            }
        } catch (Exception e) {

        }

    }//GEN-LAST:event_GuardarMaestroMouseClicked

    private void GuardarCarreraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarCarreraMouseClicked
        // TODO add your handling code here:
        try {
            if (NombresCarreras.getSelectedIndex() < 0) {
                JOptionPane.showMessageDialog(this, "No hay mas carreras que se puedan anadir!!\n"
                        + "Buen dia :)");
            } else {
                String nombre = "", facultad = "", jefeCarrera;
                int Costo;
                Costo = Integer.parseInt(CostoMensualCarrera.getText());
                jefeCarrera = JefeCarrera.getText();
                if (NombresCarreras.getSelectedItem().toString().equals("Finanzas") || NombresCarreras.getSelectedItem().toString().equals("Derecho")
                        || NombresCarreras.getSelectedItem().toString().equals("Administracion de Empresas") || NombresCarreras.getSelectedItem().toString().equals("Diseño Grafico")
                        || NombresCarreras.getSelectedItem().toString().equals("Mercadotecnia")) {
                    nombre = NombresCarreras.getSelectedItem().toString();
                    facultad = "Licenciaturas";
                } else if (NombresCarreras.getSelectedItem() == "Sistemas Computacionales" || NombresCarreras.getSelectedItem() == "Industrial" || NombresCarreras.getSelectedItem() == "Mecatronica"
                        || NombresCarreras.getSelectedItem() == "Biomedica" || NombresCarreras.getSelectedItem() == "Energia") {
                    nombre = NombresCarreras.getSelectedItem().toString();
                    facultad = "Ingenierías";
                } else if (NombresCarreras.getSelectedItem() == "Medicina" || NombresCarreras.getSelectedItem() == "Cirugía" || NombresCarreras.getSelectedItem() == "Odontología"
                        || NombresCarreras.getSelectedItem() == "Nutrición" || NombresCarreras.getSelectedItem() == "Terapia Física"
                        || NombresCarreras.getSelectedItem() == "Ocupacional") {
                    nombre = NombresCarreras.getSelectedItem().toString();
                    facultad = "Ciencias de la Salud:";
                }

                DefaultListModel modelo = (DefaultListModel) ListaCarreras.getModel();
                modelo.addElement(new Carrera(nombre, facultad, Costo, jefeCarrera));
                ListaCarreras.setModel(modelo);

                DefaultComboBoxModel modeloCarreras = (DefaultComboBoxModel) CarreraAlumno.getModel();
                modeloCarreras.addElement(new Carrera(nombre, facultad, Costo, jefeCarrera));
                CarreraAlumno.setModel(modeloCarreras);
                NombresCarreras.removeItemAt(NombresCarreras.getSelectedIndex());
                NombresCarreras.setSelectedIndex(0);
                CostoMensualCarrera.setText("");
                JefeCarrera.setText("");
                JOptionPane.showMessageDialog(this, "Se guardo con exito!!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error!!");
        }


    }//GEN-LAST:event_GuardarCarreraMouseClicked

    private void GuardarClaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarClaseMouseClicked
        // TODO add your handling code here:
        try {
            String nombre, AireAC = "", seccion;
            int edificio, salon;
            nombre = NombreClase.getText();
            seccion = (SeccionClase.getText());
            edificio = Integer.parseInt(EdificioClase.getText());
            salon = Integer.parseInt(SalonClase.getText());
            if (AireAcondicionadoClase.getSelectedItem().equals("Si")) {
                AireAC = "Si";
            } else if (AireAcondicionadoClase.getSelectedItem().equals("No")) {
                AireAC = "No";
            }

            DefaultListModel modelo = (DefaultListModel) ListaClases.getModel();
            modelo.addElement(new Clases(nombre, seccion, edificio, salon, AireAC));
            ListaClases.setModel(modelo);

            DefaultComboBoxModel modelo0 = (DefaultComboBoxModel) ClasesMaestro.getModel();
            modelo0.addElement(new Clases(nombre, seccion, edificio, salon, AireAC));
            ClasesMaestro.setModel(modelo0);

            AireAcondicionadoClase.setSelectedIndex(0);
            NombreClase.setText("");
            SeccionClase.setText("");
            SalonClase.setText("");
            JOptionPane.showMessageDialog(this, "Se guardo con exito!!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error!!");
        }

    }//GEN-LAST:event_GuardarClaseMouseClicked

    private void ApellidoMaestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoMaestroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoMaestroActionPerformed

    private void ListaMaestrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaMaestrosMouseClicked
        // TODO add your handling code here:
        if (ListaMaestros.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                Master.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_ListaMaestrosMouseClicked

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        // TODO add your handling code here:
        if (ListaMaestros.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                Master.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jTree1MouseClicked

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
           if (ListaMaestros.getSelectedIndex() >= 0) {
            DefaultListModel modelo
                    = (DefaultListModel) ListaMaestros.getModel();
            modelo.remove(ListaMaestros.getSelectedIndex());
            ListaMaestros.setModel(modelo);
            JOptionPane.showMessageDialog(this,
                    "Eliminado exitosamente");
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
        try{
            if (ListaMaestros.getSelectedIndex()>=0) {
                DefaultListModel modeloLISTA = (DefaultListModel) ListaMaestros.getModel();
                ((Maestro) modeloLISTA.get(ListaMaestros.getSelectedIndex())) .setNombre(JOptionPane.showInputDialog("Nombre"));
                ListaMaestros.setModel(modeloLISTA);
                JOptionPane.showMessageDialog(this, "Modificado exitosamente!");
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_NombreActionPerformed

    private void ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoActionPerformed
        // TODO add your handling code here:
        try{
            if (ListaMaestros.getSelectedIndex()>=0) {
                DefaultListModel modeloLISTA = (DefaultListModel) ListaMaestros.getModel();
                ((Maestro) modeloLISTA.get(ListaMaestros.getSelectedIndex())) .setApellido(JOptionPane.showInputDialog("Apellido"));
                ListaMaestros.setModel(modeloLISTA);
                JOptionPane.showMessageDialog(this, "Modificado exitosamente!");
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_ApellidoActionPerformed

    private void EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadActionPerformed
        // TODO add your handling code here:
        try{
            if (ListaMaestros.getSelectedIndex()>=0) {
                DefaultListModel modeloLISTA = (DefaultListModel) ListaMaestros.getModel();
                ((Maestro) modeloLISTA.get(ListaMaestros.getSelectedIndex())) .setEdad(Integer.parseInt(JOptionPane.showInputDialog("Edad")));
                ListaMaestros.setModel(modeloLISTA);
                JOptionPane.showMessageDialog(this, "Modificado exitosamente!");
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_EdadActionPerformed

    private void SalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalarioActionPerformed
        // TODO add your handling code here:
        try{
            if (ListaMaestros.getSelectedIndex()>=0) {
                DefaultListModel modeloLISTA = (DefaultListModel) ListaMaestros.getModel();
                ((Maestro) modeloLISTA.get(ListaMaestros.getSelectedIndex())) .setSalario(Integer.parseInt(JOptionPane.showInputDialog("Salario")));
                ListaMaestros.setModel(modeloLISTA);
                JOptionPane.showMessageDialog(this, "Modificado exitosamente!");
            }
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_SalarioActionPerformed

    private void EliminarClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarClasesActionPerformed
        // TODO add your handling code here:
        try{
           if (ListaClases.getSelectedIndex() >= 0) {
            DefaultListModel modelo
                    = (DefaultListModel) ListaClases.getModel();
            modelo.remove(ListaClases.getSelectedIndex());
            ListaClases.setModel(modelo);
            JOptionPane.showMessageDialog(this,
                    "Eliminado exitosamente");
        }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_EliminarClasesActionPerformed

    private void NombreClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreClasesActionPerformed
        // TODO add your handling code here:
        try{
            if (ListaClases.getSelectedIndex()>=0) {
                DefaultListModel modeloLISTA = (DefaultListModel) ListaClases.getModel();
                ((Clases) modeloLISTA.get(ListaClases.getSelectedIndex())) .setNombre(JOptionPane.showInputDialog("Nombre"));
                ListaClases.setModel(modeloLISTA);
                JOptionPane.showMessageDialog(this, "Modificado exitosamente!");
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_NombreClasesActionPerformed
    
    private void SeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeccionActionPerformed
        // TODO add your handling code here:
        try{
            if (ListaClases.getSelectedIndex()>=0) {
                DefaultListModel modeloLISTA = (DefaultListModel) ListaClases.getModel();
                ((Clases) modeloLISTA.get(ListaClases.getSelectedIndex())) .setSeccion(JOptionPane.showInputDialog("Seccion"));
                ListaClases.setModel(modeloLISTA);
                JOptionPane.showMessageDialog(this, "Modificado exitosamente!");
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_SeccionActionPerformed

    private void EdificionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdificionActionPerformed
        // TODO add your handling code here:
        try{
            if (ListaClases.getSelectedIndex()>=0) {
                DefaultListModel modeloLISTA = (DefaultListModel) ListaClases.getModel();
                ((Clases) modeloLISTA.get(ListaClases.getSelectedIndex())) .setEdificio(Integer.parseInt(JOptionPane.showInputDialog("Edificio")));
                ListaClases.setModel(modeloLISTA);
                JOptionPane.showMessageDialog(this, "Modificado exitosamente!");
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_EdificionActionPerformed

    private void SalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalonActionPerformed
        // TODO add your handling code here:
        try{
            if (ListaClases.getSelectedIndex()>=0) {
                DefaultListModel modeloLISTA = (DefaultListModel) ListaClases.getModel();
                ((Clases) modeloLISTA.get(ListaClases.getSelectedIndex())) .setSalon(Integer.parseInt(JOptionPane.showInputDialog("Salon")));
                ListaClases.setModel(modeloLISTA);
                JOptionPane.showMessageDialog(this, "Modificado exitosamente!");
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_SalonActionPerformed

    private void ListaAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaAlumnosMouseClicked
        // TODO add your handling code here:
        if (ListaClases.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                Clases.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_ListaAlumnosMouseClicked

    private void ListaCarrerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaCarrerasMouseClicked
        // TODO add your handling code here:
       if (ListaCarreras.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
               Carrera.show(evt.getComponent(),evt.getX(),evt.getY());
           }
        }
    }//GEN-LAST:event_ListaCarrerasMouseClicked

    private void ListaClasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaClasesMouseClicked
        // TODO add your handling code here:
        if (ListaClases.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                Clases.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_ListaClasesMouseClicked

    private void EliminarCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCarActionPerformed
        
        try{
           if (ListaCarreras.getSelectedIndex() >= 0) {
            DefaultListModel modelo
                    = (DefaultListModel) ListaCarreras.getModel();
            modelo.remove(ListaCarreras.getSelectedIndex());
            ListaCarreras.setModel(modelo);
            JOptionPane.showMessageDialog(this,
                    "Eliminado exitosamente");
        }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_EliminarCarActionPerformed

    private void SalarioModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalarioModiActionPerformed
        // TODO add your handling code here:
        try{
            if (ListaCarreras.getSelectedIndex()>=0) {
                DefaultListModel modeloLISTA = (DefaultListModel) ListaCarreras.getModel();
                ((Carrera) modeloLISTA.get(ListaCarreras.getSelectedIndex())) .setCostoMensual(Integer.parseInt(JOptionPane.showInputDialog("Costo")));
                ListaCarreras.setModel(modeloLISTA);
                JOptionPane.showMessageDialog(this, "Modificado exitosamente!");
            }
        }catch(Exception e){
            
        }
        
        
        
    }//GEN-LAST:event_SalarioModiActionPerformed

    private void JefeCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JefeCarActionPerformed
        // TODO add your handling code here:
        try{
            if (ListaCarreras.getSelectedIndex()>=0) {
                DefaultListModel modeloLISTA = (DefaultListModel) ListaCarreras.getModel();
                ((Carrera) modeloLISTA.get(ListaCarreras.getSelectedIndex())) .setJefeDeCarrera(JOptionPane.showInputDialog("Nombre Jefe"));
                ListaCarreras.setModel(modeloLISTA);
                JOptionPane.showMessageDialog(this, "Modificado exitosamente!");
            }
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_JefeCarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AireAcondicionadoClase;
    private javax.swing.JMenuItem Apellido;
    private javax.swing.JTextField ApellidoAlumno;
    private javax.swing.JTextField ApellidoMaestro;
    private javax.swing.JPopupMenu Carrera;
    private javax.swing.JComboBox<String> CarreraAlumno;
    private javax.swing.JPopupMenu Clases;
    private javax.swing.JComboBox<String> ClasesMaestro;
    private javax.swing.JFormattedTextField CostoMensualCarrera;
    private javax.swing.JMenuItem Edad;
    private javax.swing.JFormattedTextField EdadAlumno;
    private javax.swing.JFormattedTextField EdadMestro;
    private javax.swing.JFormattedTextField EdificioClase;
    private javax.swing.JMenuItem Edificion;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem EliminarCar;
    private javax.swing.JMenuItem EliminarClases;
    private javax.swing.JComboBox<String> GeneroAlumno;
    private javax.swing.JComboBox<String> GeneroMaestro;
    private javax.swing.JButton GuardarAlumno;
    private javax.swing.JButton GuardarCarrera;
    private javax.swing.JButton GuardarClase;
    private javax.swing.JButton GuardarMaestro;
    private javax.swing.JMenuItem JefeCar;
    private javax.swing.JTextField JefeCarrera;
    private javax.swing.JList<String> ListaAlumnos;
    private javax.swing.JList<String> ListaCarreras;
    private javax.swing.JList<String> ListaClases;
    private javax.swing.JList<String> ListaMaestros;
    private javax.swing.JPopupMenu Master;
    private javax.swing.JMenu Modificar;
    private javax.swing.JMenu ModificarCarrera;
    private javax.swing.JMenu ModificarClases;
    private javax.swing.JMenuItem Nombre;
    private javax.swing.JTextField NombreAlumno;
    private javax.swing.JTextField NombreClase;
    private javax.swing.JMenuItem NombreClases;
    private javax.swing.JTextField NombreMaestro;
    private javax.swing.JComboBox<String> NombresCarreras;
    private javax.swing.JMenuItem Salario;
    private javax.swing.JFormattedTextField SalarioMaestro;
    private javax.swing.JMenuItem SalarioModi;
    private javax.swing.JMenuItem Salon;
    private javax.swing.JFormattedTextField SalonClase;
    private javax.swing.JMenuItem Seccion;
    private javax.swing.JTextField SeccionClase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
    ArrayList alumnos = new ArrayList();
    ArrayList carreras = new ArrayList();
    Random ran = new Random();
}
